#!/usr/bin/sh

$HOME/.config/bspwm/autostart.sh

# bspc monitor -d 1 2 3 4 5 6 7 8
bspc monitor -d "一" "二" "三" "四" "五" "六" "七" "八"

bspc config border_width         4
bspc config window_gap          16

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#c4a7e7"
bspc config normal_border_color "#191724"
